language:
  - python

python:
  - "2.7"

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    packages:
      - python-enchant

install:
  # Info about OS
  - uname -a

  # Info about Python tools
  - which python
  - python --version

  - which virtualenv
  - virtualenv --version

  # Install Rust from archives {
  - wget https://static.rust-lang.org/dist/rust-std-1.10.0-x86_64-unknown-linux-gnu.tar.gz
  - tar xf rust-std-1.10.0-x86_64-unknown-linux-gnu.tar.gz

  - wget https://static.rust-lang.org/dist/rust-1.10.0-x86_64-unknown-linux-gnu.tar.gz
  - tar xf rust-1.10.0-x86_64-unknown-linux-gnu.tar.gz

  - >
    mv
    rust-std-1.10.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu
    rust-1.10.0-x86_64-unknown-linux-gnu/rustc/lib/rustlib
  # }

  - export PATH="`pwd`/rust-1.10.0-x86_64-unknown-linux-gnu/rustc/bin:$PATH"
  - export PATH="`pwd`/rust-1.10.0-x86_64-unknown-linux-gnu/cargo/bin:$PATH"

  - which cargo
  - cargo --version

  - which rustc
  - rustc --version

script:
  - cd docs
  - ./jenkins.sh

  - cargo build --verbose
