[package]
name = "hunter-bot"
version = "0.1.0"
authors = ["Cyberunner23 <narutoxela@gmail.com>"]

[dependencies]
hyper      = "*"
iron       = "*"
openssl    = "*"
rand       = "*"
regex      = "*"
serde      = "*"
serde_json = "*"
toml       = "*"